apiVersion: v1
kind: Service
metadata:
  name: {{ include "credit-card-validator.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "credit-card-validator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "credit-card-validator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}